#!/usr/bin/env python3
"""Validate the Orthographic Mutations collection and emit browser-ready data."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "content" / "collections" / "orthographic-mutations.json"
OUTPUT = (
    ROOT
    / "docs"
    / "production"
    / "orthographic-mutations-gallery"
    / "data.js"
)

EXPECTED_IDS = [f"OM-{number:02d}" for number in range(1, 13)]
ALLOWED_CATEGORIES = {"punctuation", "spelling", "syntax", "vernacular", "tone"}
ALLOWED_VISUALS = {
    "comma",
    "serial-comma",
    "word-gap",
    "correction-loop",
    "scramble",
    "ough-grid",
    "transposition",
    "shift-leak",
    "missing-verb",
    "grammar-tree",
    "modifier-cloud",
    "alternating-case",
}
FORBIDDEN_ASSET_KEYS = {"image", "image_url", "image_path", "asset", "src"}


def fail(message: str) -> None:
    raise SystemExit(f"Orthographic collection invalid: {message}")


def find_forbidden_asset_key(value: object, path: str = "collection") -> str | None:
    if isinstance(value, dict):
        for key, child in value.items():
            if key.lower() in FORBIDDEN_ASSET_KEYS:
                return f"{path}.{key}"
            match = find_forbidden_asset_key(child, f"{path}.{key}")
            if match:
                return match
    elif isinstance(value, list):
        for index, child in enumerate(value):
            match = find_forbidden_asset_key(child, f"{path}[{index}]")
            if match:
                return match
    return None


def registered_ids() -> set[str]:
    values: set[str] = set()
    for path in (ROOT / "content" / "specimens").glob("*.json"):
        record = json.loads(path.read_text(encoding="utf-8"))
        values.add(record["register_id"])
    return values


def validate(collection: dict[str, object]) -> None:
    if collection.get("collection_id") != "OM":
        fail("collection_id must remain OM")

    policy = collection.get("display_policy")
    if not isinstance(policy, dict) or policy.get("third_party_images") is not False:
        fail("display_policy.third_party_images must be false")

    forbidden = find_forbidden_asset_key(collection)
    if forbidden:
        fail(f"asset-bearing key found at {forbidden}")

    specimens = collection.get("specimens")
    if not isinstance(specimens, list):
        fail("specimens must be a list")
    ids = [record.get("id") for record in specimens if isinstance(record, dict)]
    if ids != EXPECTED_IDS:
        fail(f"specimen IDs must be exactly {EXPECTED_IDS}")

    slugs: set[str] = set()
    permanent_ids = registered_ids()
    required = {
        "slug",
        "title",
        "classification",
        "category",
        "period",
        "mechanism",
        "mutation",
        "epitaph",
        "curatorial_note",
        "evidence_grade",
        "source_label",
        "source_url",
        "rights_posture",
        "related_register_ids",
        "visual",
    }

    for record in specimens:
        specimen_id = record["id"]
        missing = sorted(required - record.keys())
        if missing:
            fail(f"{specimen_id} missing {', '.join(missing)}")
        if record["slug"] in slugs:
            fail(f"duplicate slug {record['slug']}")
        slugs.add(record["slug"])
        if record["category"] not in ALLOWED_CATEGORIES:
            fail(f"{specimen_id} has unknown category {record['category']}")
        if record["evidence_grade"] not in {"A", "B", "C"}:
            fail(f"{specimen_id} has invalid evidence grade")
        if not str(record["source_url"]).startswith("https://"):
            fail(f"{specimen_id} must cite an HTTPS source")
        visual = record["visual"]
        if not isinstance(visual, dict) or visual.get("kind") not in ALLOWED_VISUALS:
            fail(f"{specimen_id} has an unsupported visual")
        unknown_links = set(record["related_register_ids"]) - permanent_ids
        if unknown_links:
            fail(f"{specimen_id} links unknown register IDs {sorted(unknown_links)}")

    annex = collection.get("writers_at_work")
    if not isinstance(annex, dict):
        fail("writers_at_work must be an object")
    notes = annex.get("field_notes")
    if not isinstance(notes, list) or len(notes) != 5:
        fail("Writers at Work must contain exactly five field notes")
    if [note.get("id") for note in notes] != [f"WA-{n:02d}" for n in range(1, 6)]:
        fail("Writers at Work IDs must be WA-01 through WA-05")


def main() -> None:
    collection = json.loads(SOURCE.read_text(encoding="utf-8"))
    validate(collection)
    payload = json.dumps(collection, ensure_ascii=False, indent=2).replace("<", "\\u003c")
    output = (
        "// Generated by scripts/build_orthographic_gallery.py. Do not edit by hand.\n"
        f"window.ORTHOGRAPHIC_COLLECTION = {payload};\n"
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output, encoding="utf-8")
    print(
        f"Built {OUTPUT.relative_to(ROOT)}: "
        f"{len(collection['specimens'])} specimens + "
        f"{len(collection['writers_at_work']['field_notes'])} field notes"
    )


if __name__ == "__main__":
    main()
